# Dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 680
TILE_SIZE = 32
JAIL_WIDTH = TILE_SIZE*13
JAIL_HEIGHT = TILE_SIZE*7
JAIL_X_START = SCREEN_WIDTH//2 - JAIL_WIDTH//2
JAIL_X_END = SCREEN_WIDTH//2 + JAIL_WIDTH//2
JAIL_Y_START = SCREEN_HEIGHT//2 - JAIL_HEIGHT//2
JAIL_Y_END = SCREEN_HEIGHT//2 + JAIL_HEIGHT//2

SPRITE_RIGHT = (JAIL_X_END - TILE_SIZE // 2, SCREEN_HEIGHT // 2)
SPRITE_LEFT = (JAIL_X_START + TILE_SIZE // 2, SCREEN_HEIGHT // 2)
SPRITE_TOP = (SCREEN_WIDTH//2, JAIL_Y_START + TILE_SIZE / 2)
SPRITE_BOTTOM = (SCREEN_WIDTH // 2, JAIL_Y_END - TILE_SIZE / 2)
SPRITE_MIDDLE = (SCREEN_WIDTH // 2, SCREEN_HEIGHT // 2)

# Player stats
BASE_SPD = 4
BASE_ATK_SPD = 1000
BASE_KNIFE_SPD = 4
BASE_HP = 10
BASE_MAX_HP = 1
BASE_ATK = 10
BASE_ATK_RNG = 5

# Level scaling
LVLDMG = 2
LVL2DMG = 3

# Enemy stats
PAT_SPD = 2
PAT_ATK = 1
PAT_HP = 15

GUARD_SPD = 1
GUARD_ATK = 1
GUARD_HP = 15

SENTRY_ATK = 1
SENTRY_HP = 20

ARROW_ATK = 1
ARROW_CHANCE = 120

BP_HP = 1
BP_HP = 5
BP_SPD = 2

# Timing stuff
LAST_THROW_TIME = 0
LAST_DMG_TIME = 0
TIME_SINCE_DOOR = 0
