#dimensions
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 680
TILE_SIZE = 16
JAIL_WIDTH = TILE_SIZE*26
JAIL_HEIGHT = TILE_SIZE*14
JAIL_X_START = SCREEN_WIDTH//2 - JAIL_WIDTH//2
JAIL_X_END = SCREEN_WIDTH//2 + JAIL_WIDTH//2
JAIL_Y_START = SCREEN_HEIGHT//2 - JAIL_HEIGHT//2
JAIL_Y_END = SCREEN_HEIGHT//2 + JAIL_HEIGHT//2

#player stats
BASE_SPD = 1
BASE_ATK_SPD = 1
BASE_HP = 10
BASE_ATK = 10

#enemy stats
PAT_SPD = 2
PAT_ATK = 1
PAT_HP = 15

GUARD_SPD = 1
GUARD_ATK = 1
GUARD_HP = 15

SENTRY_SPD = 0
SENTRY_ATK = 1
SENTRY_HP = 20
